name: WaypointShrine
piecehammer: Hammer
m_name: $piece_waypoint
sizeMultiplier: 1
m_description: $piece_waypoint_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 1000
  damageModifiers:
    m_blunt: Immune
    m_slash: Immune
    m_pierce: Immune
    m_chop: Immune
    m_pickaxe: Immune
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Stone
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
build:
- SwordCheat:1:1:False
