name: fire_pit_hildir
piecehammer: Hammer
m_name: Firepit iron (everburning)
sizeMultiplier: 1
m_description: Burns eternally without fuel.
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_forge
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort:
  comfort: 1
  comfortGroup: Fire
  comfortObject: &o0
    transform:
    - []
    - []
    - []
    - []
    - []
    - []
    - - []
      - []
      - []
      - []
      - []
      - []
    layer: 10
    active: false
    activeSelf: false
    activeInHierarchy: false
    isStatic: false
    tag: Untagged
    scene:
      handle: 0
      path: 
      name: 
      isLoaded: false
      buildIndex: -1
      isDirty: false
      rootCount: 0
      isSubScene: true
    sceneCullingMask: 16140901064495857664
    gameObject: *o0
    name: _enabled_high
    hideFlags: None
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: true
wearNTearData: 
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData:
  StartFuel: 10
  MaxFuel: 10
  SecPerFuel: 5000
  InfiniteFuel: true
  FuelType: Wood
  IgniteInterval: 0
  IgniteChance: 0
  IgniteSpread: 4
teleportWorldData: 
plantData: 
shipData: 
build:
- Ironpit:1:1:True
- Wood:1:1:True
- BlackCore:1:1:True
