name: Recipe_SaddleT2
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- TrollHide:5:0:False
- DeerHide:2:0:False
- Carapace:1:0:False
