name: Recipe_SaddleT4
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- WolfPelt:6:0:False
- Crystal:2:0:False
- Silver:1:0:False
- GrizzlyBearPelt_TW:4:0:False
