name: Recipe_SaddleT3
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- DeerHide:15:0:False
- ElderBark:10:0:False
- Iron:6:0:False
- Guck:10:0:False
