name: Recipe_SaddleT0
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LeatherScraps:6:0:False
- DeerHide:4:0:False
- HardAntler:1:0:False
- Dandelion:10:0:False
