name: Recipe_SaddleT6
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ScaleHide:15:0:False
- Carapace:6:0:False
- YggdrasilWood:6:0:False
- Sap:10:0:False
- Eitr:3:0:False
