name: piece_BossStone_Eikthyr
piecehammer: Hammer
m_name: Boss Stone Eikthyr
sizeMultiplier: 1
m_description: $guardianstone_eikthyr_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 1500
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Normal
    m_spirit: Normal
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
  materialType: Stone
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
build:
- TrophyDeer:1:1:True
- Stone:50:1:True
- Flint:10:1:True
