# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

# This is my own server info atm for reference. It's not active more than when I test stuff.

Sketafuls Adventure Server:
  address: server.sketaful.se
  port: 2500
  password: password
  ispvp: true


# DO YOU RUN A SERVER BASED ON THIS MODPACK AND WANT PLAYERS TO JOIN?!  
# MESSAGE ME THE ADDRESS, PORT, PASSWORD AND THE NAME YOU LIKE IT TO BE LISTED AS AND I'LL ADD IT
# SO ALL THAT DOWNLOAD THE MODPACK WILL SEE IT WHEN STARTING THE GAME!
# 
# I CAN ADD A DISCORD OR SOMETHING IN THE NAME TO MAKE PEOPLE JOIN AND ASK FOR WHITELIST/PASSWORD 
# IF THAT'S A WHAT YOU RATHER WANT!
